Config:
    welcome-msg: true
    welcome-msg-text:
    - "&m                                                               "
    - "&aWelcome %player%! This is for testing purposes, do not mind me!"
    - "&m                                                               "