name: RhbHardcore
version: ${project.version}
main: com.rhbarber.hardcore.Hardcore
api-version: 1.18
authors: [ Rhbarber, NotEugenio_ ]
description: SUFFERING!
website: https://github.com/Rhbarber/

commands:
  rhtest:
    description: Testing
  rhb:
    description: Main Command, "kills" argument made by NotEugenio_
