name: RhbHardcore
version: ${project.version}
main: com.rhbarber.hardcore.Hardcore
api-version: 1.16
authors: [ Rhbarber ]
description: SUFFERING!
website: https://github.com/Rhbarber/

commands:
  rhtest:
    description: Probanding
  rhb:
    description: Main Command
